### ISSUE TITLE
Sprockets::FileNotFound error 

### ISSUE THREAD

**Issue by MelPierre** [ministryofjustice/moj_elements#1]
after setting up a new project and adding .bowerrc directory and running bower install. the project would not run. The js line throws up an error when the project is run
 //= require moj.tabs

couldn't find file 'moj.tabs'

**Comment by matharden** [comment]
Assuming your .bowerrc file is directing Bower dependancies to `vendor/assets` and restarted your app, you'll need to make sure you require moj.tabs from within it's sub-directories. I.e.

```
//= require build/javascripts/moj.tabs
```
